### ISSUE TITLE
Find basis price for all listed

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#13]

**Comment by efecini** [comment]
1. MicroStrategy inc. [NADQ:MSTR] : 425000000 / 38250 = $11,111.11
2. Galaxy Digital Holdings [TSX:GLXY] : 134000000 / 16651 = $8,047.56
3. Square inc. [NADQ:SQ] : 50000000 / 4709 = $10,617.96
4. HUT 8 MINING CORP [TSX:Hut-8] : 36788573 / 2954 = $12,453.81
5. Riot Blockchain, Inc. [NADQ:RIOT] : 36788573 / 2954 = $6,837.60
6. Cypherpunk Holdings Inc. [TSX:HODL] : 1630000/204 = $7,990.19
7. Argo Blockchain [LSE:ARB] : 1340000/126 = $10,634.92
8. Grayscale Bitcoin Trust [OTCQX:GBTC] : 4800000000/449596 = $10,676.25
9. 3iQ The Bitcoin Fund [TSX:QBTC.U] : 91189025/8295 = $10,993.25

**Comment by nvk** [comment]
awesome, do you have links for the those? Would be nice to link them so people can have some trust in the numbers.

**Comment by efecini** [comment]
Well, I did the calculations on google calculator🙈.
Do you want me to add links of google calculations to each base price?

**Comment by nvk** [comment]
Yeah, that's the problem. I was hoping we could use what they actually paid for by its a bit of a project. Maybe we use the dates with spot for that day like you did. MSTR is wrong for example, there were two different dates/prices for each other purchases. Their number is already correct on the site, I took from the announcements. Want to maybe take a close look and see if you can get a bit closer to the real thing? Also add the dates to that list so that we have something to refer back.

Thanks!

**Comment by efecini** [comment]
That can take a day, I am trying to dig deeper to get information about each purchase but there will be some lost information about some of the acquirements. Eventhough I appreciate the attempt to get the most detailed information about the purchases, if this research goes nowhere,most applicable approach will be **total $ paid/btc amount** imo. Let's see. Fyi.

**Comment by nvk** [comment]
np, take your time.

**Comment by FaysalM** [comment]
I started on this when Micro Strategy made its first buy. Total $paid/btc is the correct basis price tbh. 
Would suggest we add a column for amount paid also. This column code then automatically also be converted to USD via price lookups.

codepen here for something that tries to do this, could easily also extend. Values are of course hardcoded at the moment.
https://codepen.io/faysalm/pen/XWdymXX

**Comment by efecini** [comment]
Hey. I've been trying to find the most possible exact amount for the companies but it is a no go from me because most of the reports doesn't eclusively give info about the expenses for the operations like in Microstrategy's report. I think we shouldn't also add any more columns (especially if it is not applicable to all companies) and go with the average price which expenses and fees included in the buy price. Also I think it is the right way tho. For instance when I buy bitcoin, I also include the exchange fees and other expenses to the buy price. I don't know it is kinda personal. So, I am including all average prices with the companies added.
I double checked the calculations by the way. Thanks.

**MicroStrategy inc.** : 425000000 / 38250 = **$11,111.11**
**Galaxy Digital Holdings** : 134000000 / 16651 = **$8,047.56**
**Square inc.** : 50000000 / 4709 = **$10,617.96**
**HUT 8 MINING CORP** : 36788573 / 2954 = **$12,453.81**
**Voyager Digital LTD** : 7927182 / 1239 = **$6,398.04**
**Riot Blockchain, Inc.** : 7200000 / 1053 = **$6,837.60**
**DigitalX** : 874835 / 215 = **$4,069.00**
**Cypherpunk Holdings Inc.** : 1630000 / 204 = **$7,990.19**
**Argo Blockchain** : 1340000 / 126 = **$10,634.92**
**Grayscale Bitcoin Trust** : 4800000000 / 449596 = **$10,676.25**
**CoinShares** : 770170932 / 69730 = **$11,045.04**
**3iQ The Bitcoin Fund** : 91189025 / 8295 = **$10,993.25**
**BTCE** : 56721505 / 5215 = **$10,876.60**

**Comment by nvk** [comment]
thx, those were my numbers too

**Comment by nvk** [comment]
automated the color based on price, check it out.
