### ISSUE TITLE
Find Ruffer's real numbers

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#160]

**Comment by marcodiomede** [comment]
I volunteer

**Comment by marcodiomede** [comment]
Very complicated issue. For first, they don't seem to vave bought 550$ million BTC. They acquired a 550$ milion exposure to BTC https://www.lse.co.uk/rns/RICA/monthly-investment-report-december-2020-y696o2ginl8o4vf.html?page=15&cmpredirect

That includes equity holdings in Microstrategy and Galaxy Digital as well as direct investment via ruffer funds
https://www.theblockcrypto.com/linked/91590/ruffer-institutional-adoption-bitcoin
This article cites a 15 dec. regulatory filling that I didn't find.

It is likely that ruffer investment has to be at least partly removed because it includes already listed public companies (MSTR & GLXY).

Still looking for more info!

**Comment by nvk** [comment]
going to pass for now.
