### ISSUE TITLE
Coinbase S1

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#186]
• As of end of 2020, Coinbase had cash and cash equivalents of $1.1 billion
• $48.9 million of USDC
• Held the following crypto: $130.1M of Bitcoin, $23.8M of Ethereum and $34.0M of other
https://twitter.com/lawmaster/status/1364919798682034177?s=21

**Comment by FracturedWinter** [comment]
- [ ] Name: Coinbase Global, Inc. 
- [ ] Exchange: symbol NASDAQ: COIN
- [ ] Link to google finance: public trading has not commenced yet
- [ ] Bitcoin Purchase Basis price: Unknown. Corporate blog implies some portion has been held since 2012.  https://blog.coinbase.com/coinbase-offers-corporations-a-trusted-solution-for-adding-crypto-to-their-corporate-treasury-1f9ceddc607d

- [ ] Market Cap: N/A
- [ ] Total BTC: ~4,487 BTC = $130.1 million / Coinbase Price at 12/31: $28,990
- [ ] Direct link to latest financial report: https://www.sec.gov/Archives/edgar/data/1679788/000162828021003168/0001628280-21-003168-index.htm

**Comment by bgrobbins** [comment]
like Voyager, I feel these crypto holdings are just a reflection of what they are holding for their customers.  If you list Voyager and Coinbase on this list, then you should list every custodian.  While Voyager and Coinbase may "hold" this crypto, I don't think they are the "owners", and I would hope you are trying to show ownership on this site.

**Comment by nvk** [comment]
Added as priv for now.
@bgrobbins that's incorrect, this 4K coins are on the balance sheet not as AUM
