### ISSUE TITLE
MassMutual 100M$ purchase

### ISSUE THREAD

**Issue by vbhangui** [nvk/bitcointreasuries.org#84]
- [ ] Market Cap: $100M USD

- [ ] https://www.wsj.com/articles/massmutual-joins-the-bitcoin-club-with-100-million-purchase-11607626800

**Comment by cgimmer** [comment]
Here's the link to the official press release:

https://www.massmutual.com/about-us/news-and-press-releases/press-releases/2020/12/institutional-bitcoin-provider-nydig-announces-minority-stake-purchase-by-massmutual

**Comment by nvk** [comment]
None of the links have the official rate they paid, purchase could have been weeks ago... waiting for numbers.

**Comment by ZurMaD** [comment]
https://www.coindesk.com/massmutual-buys-100m-bitcoin-bets-on-institutional-adoption-with-5m-nydig-stake

**Comment by LukeParker** [comment]
I think Insurance needs it's own category. That $100m doesn't go to the company's balance sheet at all; it goes into a fund for your grandparents. Normies. Nocoiners. They become the owners when they choose the "high risk" fund at Mass Mutual.

Interestingly, the high risk fund at MM will be the only one this year that isn't in the red. It's going to be extremely popular because the typical insurance fund customer never chooses funds that are currently in the red. Maybe 1% of them, that's it. This timing with the Brrr is so awesome for bitcoin in many ways.

Insurance companies are extremely competitive with their assets, too. If one company picks up a new, high-performing asset, all the others are going to jump on it quickly in fear that their own customers will switch insurance companies to get some in their fund. And the moment they do, they send out a rep to every financial advisor's office to educate them on the new asset, and those FAs all call every one of their clients to sell the new fund to them, so basically everyone who has an FA is about to get a call about Bitcoin. 

This Mass Mutual news may be the biggest news of the year for this reason; it gets everyone, every retiree, every insurance customer worldwide to hear a sales pitch from their asset management company or insurance company for bitcoin. & Then easily hold it if they say yes.

**Comment by nvk** [comment]
Waiting for formal info to know whats what.
