### ISSUE TITLE
Ruffer 2.5% of 20B?

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#90]
https://twitter.com/Bloqport/status/1338927880559058944?s=20

**Comment by tboydsto** [comment]
Correction to Twitter 

https://www.nasdaq.com/articles/ruffer-investment-allocated-2.5-of-multi-strategies-fund-to-bitcoin-in-november-2020-12-15

**Comment by tboydsto** [comment]
Ruffer announcement

https://otp.tools.investis.com/clients/uk/ruffer/rns/regulatory-story.aspx?cid=2529&newsid=1436490

Could not find financial report with Bitcoin listed

**Comment by HansHauge** [comment]
https://www.coindesk.com/ruffer-confirms-744m-bitcoin-investment

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1339233872677105671?s=20

**Comment by HansHauge** [comment]
Hey @nvk I posted a tweet right before this update. It looks like the total BTC increased by only 5k, rather than 45k. Is something not adding up in the sheet?

<img width="971" alt="Screen Shot 2020-12-16 at 7 58 04 AM" src="https://user-images.githubusercontent.com/3742367/102376410-7666b500-3f78-11eb-8e23-d7094255fb09.png">

Or maybe someone sold some of their holdings?

<img width="966" alt="Screen Shot 2020-12-16 at 9 27 07 AM" src="https://user-images.githubusercontent.com/3742367/102376470-87172b00-3f78-11eb-84d6-dfb18925f49a.png">

**Comment by HansHauge** [comment]
When I total the columns I get 937,886.6 BTC. Seems like almost 45k is missing, unless. I messed up on the addition.

**Comment by nvk** [comment]
Yes, was fixed https://twitter.com/BTCtreasuries/status/1339249234881765379?s=20
